# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'bbdwh-sql'         # name of database
      MYSQL_USER: 'uuuuuu'                # sample is the name of user
      MYSQL_PASSWORD: 'xxxxx'          # password for sample user
      MYSQL_ROOT_PASSWORD: 'xxxxx'     # password for root user
    ports:
      - '3306:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
        mysql-db:
