{
 "title": "EDA Energy Dashboard Alt",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Consumption Today",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select ((max(e.Total)-min(e.Total))+(max(s.total)-min(s.total))-(max(e.TotalReturned)-min(e.TotalReturned)))/1000 as Consumed, (max(e.Total)-min(e.Total))/1000 as Billed from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= curdate()\r\n"
    }
   ]
  },
  {
   "title": "Solar Generation Today",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select (max(s.Total)-min(s.Total))/1000 as 'Solar Generated', (max(e.TotalReturned)-min(e.TotalReturned))/1000 as 'Solar Returned' from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= curdate()\r\n"
    }
   ]
  },
  {
   "title": "Consumption Last 7 days",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select ((max(e.Total)-min(e.Total))+(max(s.total)-min(s.total))-(max(e.TotalReturned)-min(e.TotalReturned)))/1000 as Consumed, (max(e.Total)-min(e.Total))/1000 as Billed from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 6 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Solar Generation Last 7 days",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select (max(s.Total)-min(s.Total))/1000 as 'Solar Generated', (max(e.TotalReturned)-min(e.TotalReturned))/1000 as 'Solar Returned' from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 6 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Consumption Last 30 days",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select ((max(e.Total)-min(e.Total))+(max(s.total)-min(s.total))-(max(e.TotalReturned)-min(e.TotalReturned)))/1000 as Consumed, (max(e.Total)-min(e.Total))/1000 as Billed from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 29 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Solar Generation Last 30 days",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select (max(s.Total)-min(s.Total))/1000 as 'Solar Generated', (max(e.TotalReturned)-min(e.TotalReturned))/1000 as 'Solar Returned' from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 29 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Consumption Last 365 days",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select ((max(e.Total)-min(e.Total))+(max(s.total)-min(s.total))-(max(e.TotalReturned)-min(e.TotalReturned)))/1000 as Consumed, (max(e.Total)-min(e.Total))/1000 as Billed from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 364 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Solar Generation Last 365 days",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select (max(s.Total)-min(s.Total))/1000 as 'Solar Generated', (max(e.TotalReturned)-min(e.TotalReturned))/1000 as 'Solar Returned' from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 364 DAY);\r\n"
    }
   ]
  }
 ]
}