{
 "title": "EDM Energy Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Totlal Consumption Today (Billed+Used Solar)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select ((max(e.Total)-min(e.Total))+(max(s.total)-min(s.total))-(max(e.TotalReturned)-min(e.TotalReturned)))/1000 from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= curdate()\r\n"
    }
   ]
  },
  {
   "title": "Billed Consumption Today",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(Total)-min(Total))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= curdate() limit  1000000\r\n"
    }
   ]
  },
  {
   "title": "Solar Generation Today",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT max(Total) as maxSolar, min(Total) as minSolar FROM `bbdwh-sql`.EnergySolar WHERE TimeStamp >= curdate() limit  1000000"
    }
   ]
  },
  {
   "title": "Solar Returned to Grid Today",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(TotalReturned)-min(TotalReturned))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= curdate() limit  1000000"
    }
   ]
  },
  {
   "title": "Totlal Consumption Last 7 days (Billed+Used Solar)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select ((max(e.Total)-min(e.Total))+(max(s.total)-min(s.total))-(max(e.TotalReturned)-min(e.TotalReturned)))/1000 from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 6 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Billed Consumption Last 7 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(Total)-min(Total))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 6 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Solar Generation Last 7 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT max(Total) as maxSolar, min(Total) as minSolar FROM `bbdwh-sql`.EnergySolar WHERE TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 6 DAY);"
    }
   ]
  },
  {
   "title": "Solar Returned to Grid Last 7 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(TotalReturned)-min(TotalReturned))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 6 DAY);"
    }
   ]
  },
  {
   "title": "Totlal Consumption 30 days (Billed+Used Solar)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select ((max(e.Total)-min(e.Total))+(max(s.total)-min(s.total))-(max(e.TotalReturned)-min(e.TotalReturned)))/1000 from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 29 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Billed Consumption Last 30 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(Total)-min(Total))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 29 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Solar Generation Last 30 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT max(Total) as maxSolar, min(Total) as minSolar FROM `bbdwh-sql`.EnergySolar WHERE TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 29 DAY);"
    }
   ]
  },
  {
   "title": "Solar Returned to Grid Last 30 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(TotalReturned)-min(TotalReturned))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 29 DAY);"
    }
   ]
  },
  {
   "title": "Totlal Consumption 365 days (Billed+Used Solar)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select ((max(e.Total)-min(e.Total))+(max(s.total)-min(s.total))-(max(e.TotalReturned)-min(e.TotalReturned)))/1000 from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 364 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Billed Consumption Last 365 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(Total)-min(Total))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 364 DAY);\r\n"
    }
   ]
  },
  {
   "title": "Solar Generation Last 365 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT max(Total) as maxSolar, min(Total) as minSolar FROM `bbdwh-sql`.EnergySolar WHERE TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 364 DAY);"
    }
   ]
  },
  {
   "title": "Solar Returned to Grid Last 365 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(TotalReturned)-min(TotalReturned))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= DATE_SUB(CURDATE(), INTERVAL 364 DAY);"
    }
   ]
  }
 ]
}