{
 "title": "EOD Energy Overview (daily)",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Energy Consumption from & Feed to Grid",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT date(TimeStamp),(max(Total)-min(Total))/1000 as DailyTotal FROM `bbdwh-sql`.EnergyMain where TimeStamp >= $__timeFrom() and TimeStamp <= $__timeTo() group by date(timestamp);"
    }
   ]
  },
  {
   "title": "Solar Generation",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT date(TimeStamp),(max(Total)-min(Total))/1000 as DailyTotal FROM `bbdwh-sql`.EnergySolar where TimeStamp >= $__timeFrom() and TimeStamp <= $__timeTo() group by date(timestamp);"
    }
   ]
  },
  {
   "title": "Total Consumption During Period",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(Total)-min(Total))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= $__timeFrom() and TimeStamp <= $__timeTo();\r\n\r\n"
    }
   ]
  },
  {
   "title": "Solar Generation During Period",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(Total)-min(Total))/1000 as MonthlySolar FROM `bbdwh-sql`.EnergySolar WHERE TimeStamp >= $__timeFrom() and TimeStamp <= $__timeTo();"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT date(TimeStamp), min(Voltage),max(Voltage),avg(Voltage) FROM `bbdwh-sql`.EnergyMain where TimeStamp >= $__timeFrom() and TimeStamp <= $__timeTo() group by date(timestamp);"
    }
   ]
  }
 ]
}