{
 "title": "EOm Energy Overview (minutely) Compact",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Energy Consumption from & Feed to Grid",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT TimeStamp, Power FROM `bbdwh-sql`.EnergyMain LIMIT 1000000"
    }
   ]
  },
  {
   "title": "Solar Generation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT TimeStamp, Power FROM `bbdwh-sql`.EnergySolar LIMIT 1000000"
    }
   ]
  },
  {
   "title": "Totlal Consumption Today (Billed+Used Solar)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "select ((max(e.Total)-min(e.Total))+(max(s.total)-min(s.total))-(max(e.TotalReturned)-min(e.TotalReturned)))/1000 from EnergyMain as e join EnergySolar as s on date(e.timestamp) = date(s.timestamp) where e.TimeStamp >= curdate()\r\n"
    }
   ]
  },
  {
   "title": "Billed Consumption Today",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(Total)-min(Total))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= curdate() limit  1000000\r\n"
    }
   ]
  },
  {
   "title": "Solar Generation Today",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT max(Total) as maxSolar, min(Total) as minSolar FROM `bbdwh-sql`.EnergySolar WHERE TimeStamp >= curdate() limit  1000000"
    }
   ]
  },
  {
   "title": "Solar Returned to Grid Today",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT (max(TotalReturned)-min(TotalReturned))/1000 FROM `bbdwh-sql`.EnergyMain WHERE TimeStamp >= curdate() limit  1000000"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT TimeStamp,  Voltage FROM `bbdwh-sql`.EnergyMain LIMIT 1000000"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT TimeStamp, Powerfactor FROM `bbdwh-sql`.EnergyMain LIMIT 1000000"
    }
   ]
  }
 ]
}