{
 "title": "HOm Heating Overview (minutely) Compact",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Downstairs Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT TimeStamp, TempExt, TempLounge, TempHall, TempDatactr FROM `bbdwh-sql`.EnviroCond LIMIT 1000000"
    }
   ]
  },
  {
   "title": "Downstairs Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT TimeStamp, TempExt, TempBedroom FROM `bbdwh-sql`.EnviroCond LIMIT 1000000"
    }
   ]
  },
  {
   "title": "Downstairs Heating",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT TimeStamp,  DownOnpercentage FROM `bbdwh-sql`.BoilerStats LIMIT 1000000"
    }
   ]
  },
  {
   "title": "Upstairs Heating",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT TimeStamp,  UpOnpercentage FROM `bbdwh-sql`.BoilerStats LIMIT 1000000"
    }
   ]
  },
  {
   "title": "Downstairs Heating Cycles",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT TimeStamp,  DownOnctr FROM `bbdwh-sql`.BoilerStats LIMIT 1000000"
    }
   ]
  },
  {
   "title": "Upstairs Heating Cycles",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "dataset": "`bbdwh-sql`",
     "rawSql": "SELECT TimeStamp,  UpOnctr FROM `bbdwh-sql`.BoilerStats LIMIT 1000000"
    }
   ]
  }
 ]
}